[package]
name = "gicel"
version = "0.1.0"
description = "Language support for GICEL (Go's Indexed Capability Effect Language)"
authors = ["cwd-k2 <cwd-k2@users.noreply.github.com>"]
repository = "https://github.com/cwd-k2/zed-gicel"
schema_version = 1

[grammars.gicel]
repository = "https://github.com/cwd-k2/tree-sitter-gicel"
commit = "cd31c00c59ff7cdb9902ef8da18f6ea0779c93e6"
